service: standard-cv-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
  apiGateway:
    apiKeys:
      - name: myApiKey  # Nombre de la API Key

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /item
          method: post
      - http:
          path: /item/{id}
          method: get
      - http:
          path: /item/{id}
          method: put
      - http:
          path: /item/{id}
          method: delete
          private: true  # Marcar DELETE como privado, requiere API Key
      - http:
          path: /items
          method: get

resources:
  Resources:
    MyDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "StandardCvTable"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
